# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/bret.ui'
#
# Created: Sun Sep  7 19:02:25 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CentralWidget(object):
    def setupUi(self, CentralWidget):
        CentralWidget.setObjectName(_fromUtf8("CentralWidget"))
        CentralWidget.resize(563, 561)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("BRET-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CentralWidget.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(CentralWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.RegExpGroupBox = QtGui.QGroupBox(CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegExpGroupBox.sizePolicy().hasHeightForWidth())
        self.RegExpGroupBox.setSizePolicy(sizePolicy)
        self.RegExpGroupBox.setObjectName(_fromUtf8("RegExpGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.RegExpGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.RegExpLabel = QtGui.QLabel(self.RegExpGroupBox)
        self.RegExpLabel.setObjectName(_fromUtf8("RegExpLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.RegExpLabel)
        self.RegExpLayout = QtGui.QHBoxLayout()
        self.RegExpLayout.setObjectName(_fromUtf8("RegExpLayout"))
        self.RegExpLineEdit = QtGui.QLineEdit(self.RegExpGroupBox)
        self.RegExpLineEdit.setObjectName(_fromUtf8("RegExpLineEdit"))
        self.RegExpLayout.addWidget(self.RegExpLineEdit)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.RegExpLayout)
        self.RegExpOptionsLabel = QtGui.QLabel(self.RegExpGroupBox)
        self.RegExpOptionsLabel.setObjectName(_fromUtf8("RegExpOptionsLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.RegExpOptionsLabel)
        self.RegExpOptionsLayout = QtGui.QHBoxLayout()
        self.RegExpOptionsLayout.setObjectName(_fromUtf8("RegExpOptionsLayout"))
        self.IgnoreCasePushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.IgnoreCasePushButton.setCheckable(True)
        self.IgnoreCasePushButton.setObjectName(_fromUtf8("IgnoreCasePushButton"))
        self.RegExpOptionsLayout.addWidget(self.IgnoreCasePushButton)
        self.MultiLinePushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.MultiLinePushButton.setCheckable(True)
        self.MultiLinePushButton.setObjectName(_fromUtf8("MultiLinePushButton"))
        self.RegExpOptionsLayout.addWidget(self.MultiLinePushButton)
        self.DotAllPushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.DotAllPushButton.setCheckable(True)
        self.DotAllPushButton.setObjectName(_fromUtf8("DotAllPushButton"))
        self.RegExpOptionsLayout.addWidget(self.DotAllPushButton)
        self.ASCIIOnlyPushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.ASCIIOnlyPushButton.setCheckable(True)
        self.ASCIIOnlyPushButton.setObjectName(_fromUtf8("ASCIIOnlyPushButton"))
        self.RegExpOptionsLayout.addWidget(self.ASCIIOnlyPushButton)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.RegExpOptionsLayout)
        self.verticalLayout_3.addWidget(self.RegExpGroupBox)
        self.MethodTabWidget = QtGui.QTabWidget(CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MethodTabWidget.sizePolicy().hasHeightForWidth())
        self.MethodTabWidget.setSizePolicy(sizePolicy)
        self.MethodTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.MethodTabWidget.setObjectName(_fromUtf8("MethodTabWidget"))
        self.TextTab = QtGui.QWidget()
        self.TextTab.setObjectName(_fromUtf8("TextTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.TextTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.TextEdit = QtGui.QPlainTextEdit(self.TextTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit.sizePolicy().hasHeightForWidth())
        self.TextEdit.setSizePolicy(sizePolicy)
        self.TextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.TextEdit.setObjectName(_fromUtf8("TextEdit"))
        self.horizontalLayout_2.addWidget(self.TextEdit)
        self.TextTabButtonsLayout = QtGui.QVBoxLayout()
        self.TextTabButtonsLayout.setObjectName(_fromUtf8("TextTabButtonsLayout"))
        self.PasteTextPushButton = QtGui.QPushButton(self.TextTab)
        self.PasteTextPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasteTextPushButton.sizePolicy().hasHeightForWidth())
        self.PasteTextPushButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-paste"))
        self.PasteTextPushButton.setIcon(icon)
        self.PasteTextPushButton.setObjectName(_fromUtf8("PasteTextPushButton"))
        self.TextTabButtonsLayout.addWidget(self.PasteTextPushButton)
        self.ResetTextPushButton = QtGui.QPushButton(self.TextTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.ResetTextPushButton.setIcon(icon)
        self.ResetTextPushButton.setObjectName(_fromUtf8("ResetTextPushButton"))
        self.TextTabButtonsLayout.addWidget(self.ResetTextPushButton)
        self.horizontalLayout_2.addLayout(self.TextTabButtonsLayout)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("text-field"))
        self.MethodTabWidget.addTab(self.TextTab, icon, _fromUtf8(""))
        self.FileTab = QtGui.QWidget()
        self.FileTab.setObjectName(_fromUtf8("FileTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.FileTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.FilePathLineEdit = QtGui.QLineEdit(self.FileTab)
        self.FilePathLineEdit.setObjectName(_fromUtf8("FilePathLineEdit"))
        self.horizontalLayout_3.addWidget(self.FilePathLineEdit)
        self.FilePathPushButton = QtGui.QPushButton(self.FileTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.FilePathPushButton.setIcon(icon)
        self.FilePathPushButton.setObjectName(_fromUtf8("FilePathPushButton"))
        self.horizontalLayout_3.addWidget(self.FilePathPushButton)
        self.ResetFilePathPushButton = QtGui.QPushButton(self.FileTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.ResetFilePathPushButton.setIcon(icon)
        self.ResetFilePathPushButton.setObjectName(_fromUtf8("ResetFilePathPushButton"))
        self.horizontalLayout_3.addWidget(self.ResetFilePathPushButton)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-import"))
        self.MethodTabWidget.addTab(self.FileTab, icon, _fromUtf8(""))
        self.URLTab = QtGui.QWidget()
        self.URLTab.setObjectName(_fromUtf8("URLTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.URLTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.URLLayout = QtGui.QHBoxLayout()
        self.URLLayout.setObjectName(_fromUtf8("URLLayout"))
        self.URLLineEdit = QtGui.QLineEdit(self.URLTab)
        self.URLLineEdit.setObjectName(_fromUtf8("URLLineEdit"))
        self.URLLayout.addWidget(self.URLLineEdit)
        self.PasteURLPushButton = QtGui.QPushButton(self.URLTab)
        self.PasteURLPushButton.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-paste"))
        self.PasteURLPushButton.setIcon(icon)
        self.PasteURLPushButton.setObjectName(_fromUtf8("PasteURLPushButton"))
        self.URLLayout.addWidget(self.PasteURLPushButton)
        self.ResetURLPushButton = QtGui.QPushButton(self.URLTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.ResetURLPushButton.setIcon(icon)
        self.ResetURLPushButton.setObjectName(_fromUtf8("ResetURLPushButton"))
        self.URLLayout.addWidget(self.ResetURLPushButton)
        self.verticalLayout_4.addLayout(self.URLLayout)
        self.DownloadProgressBar = QtGui.QProgressBar(self.URLTab)
        self.DownloadProgressBar.setProperty("value", 0)
        self.DownloadProgressBar.setObjectName(_fromUtf8("DownloadProgressBar"))
        self.verticalLayout_4.addWidget(self.DownloadProgressBar)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("download"))
        self.MethodTabWidget.addTab(self.URLTab, icon, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.MethodTabWidget)
        self.ResultsTabWidget = QtGui.QTabWidget(CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultsTabWidget.sizePolicy().hasHeightForWidth())
        self.ResultsTabWidget.setSizePolicy(sizePolicy)
        self.ResultsTabWidget.setObjectName(_fromUtf8("ResultsTabWidget"))
        self.MatchesTab = QtGui.QWidget()
        self.MatchesTab.setObjectName(_fromUtf8("MatchesTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.MatchesTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.MatchesLayout = QtGui.QHBoxLayout()
        self.MatchesLayout.setObjectName(_fromUtf8("MatchesLayout"))
        self.MatchesLimitLabel = QtGui.QLabel(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatchesLimitLabel.sizePolicy().hasHeightForWidth())
        self.MatchesLimitLabel.setSizePolicy(sizePolicy)
        self.MatchesLimitLabel.setObjectName(_fromUtf8("MatchesLimitLabel"))
        self.MatchesLayout.addWidget(self.MatchesLimitLabel)
        self.MatchesLimitSpinBox = QtGui.QSpinBox(self.MatchesTab)
        self.MatchesLimitSpinBox.setEnabled(False)
        self.MatchesLimitSpinBox.setMinimum(1)
        self.MatchesLimitSpinBox.setObjectName(_fromUtf8("MatchesLimitSpinBox"))
        self.MatchesLayout.addWidget(self.MatchesLimitSpinBox)
        self.NoMatchesLimitCheckBox = QtGui.QCheckBox(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoMatchesLimitCheckBox.sizePolicy().hasHeightForWidth())
        self.NoMatchesLimitCheckBox.setSizePolicy(sizePolicy)
        self.NoMatchesLimitCheckBox.setChecked(True)
        self.NoMatchesLimitCheckBox.setObjectName(_fromUtf8("NoMatchesLimitCheckBox"))
        self.MatchesLayout.addWidget(self.NoMatchesLimitCheckBox)
        self.GroupsCheckBox = QtGui.QCheckBox(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupsCheckBox.sizePolicy().hasHeightForWidth())
        self.GroupsCheckBox.setSizePolicy(sizePolicy)
        self.GroupsCheckBox.setObjectName(_fromUtf8("GroupsCheckBox"))
        self.MatchesLayout.addWidget(self.GroupsCheckBox)
        self.PositionsCheckBox = QtGui.QCheckBox(self.MatchesTab)
        self.PositionsCheckBox.setObjectName(_fromUtf8("PositionsCheckBox"))
        self.MatchesLayout.addWidget(self.PositionsCheckBox)
        self.verticalLayout.addLayout(self.MatchesLayout)
        self.MatchesTreeView = QtGui.QTreeView(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatchesTreeView.sizePolicy().hasHeightForWidth())
        self.MatchesTreeView.setSizePolicy(sizePolicy)
        self.MatchesTreeView.setObjectName(_fromUtf8("MatchesTreeView"))
        self.verticalLayout.addWidget(self.MatchesTreeView)
        self.MatchesButtonsLayout = QtGui.QHBoxLayout()
        self.MatchesButtonsLayout.setObjectName(_fromUtf8("MatchesButtonsLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.MatchesButtonsLayout.addItem(spacerItem)
        self.FindMatchesPushButton = QtGui.QPushButton(self.MatchesTab)
        self.FindMatchesPushButton.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find"))
        self.FindMatchesPushButton.setIcon(icon)
        self.FindMatchesPushButton.setDefault(True)
        self.FindMatchesPushButton.setObjectName(_fromUtf8("FindMatchesPushButton"))
        self.MatchesButtonsLayout.addWidget(self.FindMatchesPushButton)
        self.ResetMatchesPushButton = QtGui.QPushButton(self.MatchesTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.ResetMatchesPushButton.setIcon(icon)
        self.ResetMatchesPushButton.setObjectName(_fromUtf8("ResetMatchesPushButton"))
        self.MatchesButtonsLayout.addWidget(self.ResetMatchesPushButton)
        self.verticalLayout.addLayout(self.MatchesButtonsLayout)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find"))
        self.ResultsTabWidget.addTab(self.MatchesTab, icon, _fromUtf8(""))
        self.ReplaceTab = QtGui.QWidget()
        self.ReplaceTab.setObjectName(_fromUtf8("ReplaceTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ReplaceTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ReplacementTextLayout = QtGui.QHBoxLayout()
        self.ReplacementTextLayout.setObjectName(_fromUtf8("ReplacementTextLayout"))
        self.ReplacementTextLabel = QtGui.QLabel(self.ReplaceTab)
        self.ReplacementTextLabel.setObjectName(_fromUtf8("ReplacementTextLabel"))
        self.ReplacementTextLayout.addWidget(self.ReplacementTextLabel)
        self.ReplacementTextLineEdit = QtGui.QLineEdit(self.ReplaceTab)
        self.ReplacementTextLineEdit.setObjectName(_fromUtf8("ReplacementTextLineEdit"))
        self.ReplacementTextLayout.addWidget(self.ReplacementTextLineEdit)
        self.verticalLayout_2.addLayout(self.ReplacementTextLayout)
        self.ReplacementsLayout = QtGui.QHBoxLayout()
        self.ReplacementsLayout.setObjectName(_fromUtf8("ReplacementsLayout"))
        self.ReplacementsLimitLabel = QtGui.QLabel(self.ReplaceTab)
        self.ReplacementsLimitLabel.setObjectName(_fromUtf8("ReplacementsLimitLabel"))
        self.ReplacementsLayout.addWidget(self.ReplacementsLimitLabel)
        self.ReplacementsLimitSpinBox = QtGui.QSpinBox(self.ReplaceTab)
        self.ReplacementsLimitSpinBox.setEnabled(False)
        self.ReplacementsLimitSpinBox.setMinimum(1)
        self.ReplacementsLimitSpinBox.setObjectName(_fromUtf8("ReplacementsLimitSpinBox"))
        self.ReplacementsLayout.addWidget(self.ReplacementsLimitSpinBox)
        self.NoReplacementsLimitCheckBox = QtGui.QCheckBox(self.ReplaceTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoReplacementsLimitCheckBox.sizePolicy().hasHeightForWidth())
        self.NoReplacementsLimitCheckBox.setSizePolicy(sizePolicy)
        self.NoReplacementsLimitCheckBox.setChecked(True)
        self.NoReplacementsLimitCheckBox.setObjectName(_fromUtf8("NoReplacementsLimitCheckBox"))
        self.ReplacementsLayout.addWidget(self.NoReplacementsLimitCheckBox)
        self.NumberOfReplacementsLabel = QtGui.QLabel(self.ReplaceTab)
        self.NumberOfReplacementsLabel.setText(_fromUtf8(""))
        self.NumberOfReplacementsLabel.setObjectName(_fromUtf8("NumberOfReplacementsLabel"))
        self.ReplacementsLayout.addWidget(self.NumberOfReplacementsLabel)
        self.verticalLayout_2.addLayout(self.ReplacementsLayout)
        self.ReplacementsPlainTextEdit = QtGui.QPlainTextEdit(self.ReplaceTab)
        self.ReplacementsPlainTextEdit.setReadOnly(True)
        self.ReplacementsPlainTextEdit.setObjectName(_fromUtf8("ReplacementsPlainTextEdit"))
        self.verticalLayout_2.addWidget(self.ReplacementsPlainTextEdit)
        self.ReplaceButtonsLayout = QtGui.QHBoxLayout()
        self.ReplaceButtonsLayout.setObjectName(_fromUtf8("ReplaceButtonsLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ReplaceButtonsLayout.addItem(spacerItem1)
        self.ReplacePushButton = QtGui.QPushButton(self.ReplaceTab)
        self.ReplacePushButton.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find-replace"))
        self.ReplacePushButton.setIcon(icon)
        self.ReplacePushButton.setDefault(True)
        self.ReplacePushButton.setObjectName(_fromUtf8("ReplacePushButton"))
        self.ReplaceButtonsLayout.addWidget(self.ReplacePushButton)
        self.ResetReplacementsPushButton = QtGui.QPushButton(self.ReplaceTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.ResetReplacementsPushButton.setIcon(icon)
        self.ResetReplacementsPushButton.setObjectName(_fromUtf8("ResetReplacementsPushButton"))
        self.ReplaceButtonsLayout.addWidget(self.ResetReplacementsPushButton)
        self.verticalLayout_2.addLayout(self.ReplaceButtonsLayout)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find-replace"))
        self.ResultsTabWidget.addTab(self.ReplaceTab, icon, _fromUtf8(""))
        self.SplitTab = QtGui.QWidget()
        self.SplitTab.setObjectName(_fromUtf8("SplitTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.SplitTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.SplitsLimitLabel = QtGui.QLabel(self.SplitTab)
        self.SplitsLimitLabel.setObjectName(_fromUtf8("SplitsLimitLabel"))
        self.horizontalLayout_5.addWidget(self.SplitsLimitLabel)
        self.SplitsLimitSpinBox = QtGui.QSpinBox(self.SplitTab)
        self.SplitsLimitSpinBox.setEnabled(False)
        self.SplitsLimitSpinBox.setMinimum(1)
        self.SplitsLimitSpinBox.setObjectName(_fromUtf8("SplitsLimitSpinBox"))
        self.horizontalLayout_5.addWidget(self.SplitsLimitSpinBox)
        self.NoSplitsLimitCheckBox = QtGui.QCheckBox(self.SplitTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoSplitsLimitCheckBox.sizePolicy().hasHeightForWidth())
        self.NoSplitsLimitCheckBox.setSizePolicy(sizePolicy)
        self.NoSplitsLimitCheckBox.setChecked(True)
        self.NoSplitsLimitCheckBox.setObjectName(_fromUtf8("NoSplitsLimitCheckBox"))
        self.horizontalLayout_5.addWidget(self.NoSplitsLimitCheckBox)
        self.NumberOfSplitsLabel = QtGui.QLabel(self.SplitTab)
        self.NumberOfSplitsLabel.setText(_fromUtf8(""))
        self.NumberOfSplitsLabel.setObjectName(_fromUtf8("NumberOfSplitsLabel"))
        self.horizontalLayout_5.addWidget(self.NumberOfSplitsLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.SplitResultsListView = QtGui.QListView(self.SplitTab)
        self.SplitResultsListView.setObjectName(_fromUtf8("SplitResultsListView"))
        self.verticalLayout_5.addWidget(self.SplitResultsListView)
        self.SplitButtonsLayout = QtGui.QHBoxLayout()
        self.SplitButtonsLayout.setObjectName(_fromUtf8("SplitButtonsLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.SplitButtonsLayout.addItem(spacerItem2)
        self.SplitPushButton = QtGui.QPushButton(self.SplitTab)
        self.SplitPushButton.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-cut"))
        self.SplitPushButton.setIcon(icon)
        self.SplitPushButton.setDefault(True)
        self.SplitPushButton.setObjectName(_fromUtf8("SplitPushButton"))
        self.SplitButtonsLayout.addWidget(self.SplitPushButton)
        self.ResetSplitPushButton = QtGui.QPushButton(self.SplitTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.ResetSplitPushButton.setIcon(icon)
        self.ResetSplitPushButton.setObjectName(_fromUtf8("ResetSplitPushButton"))
        self.SplitButtonsLayout.addWidget(self.ResetSplitPushButton)
        self.verticalLayout_5.addLayout(self.SplitButtonsLayout)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-cut"))
        self.ResultsTabWidget.addTab(self.SplitTab, icon, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.ResultsTabWidget)
        self.RegExpLabel.setBuddy(self.RegExpLineEdit)
        self.MatchesLimitLabel.setBuddy(self.MatchesLimitSpinBox)
        self.ReplacementTextLabel.setBuddy(self.ReplacementTextLineEdit)
        self.ReplacementsLimitLabel.setBuddy(self.ReplacementsLimitSpinBox)
        self.SplitsLimitLabel.setBuddy(self.SplitsLimitSpinBox)

        self.retranslateUi(CentralWidget)
        self.MethodTabWidget.setCurrentIndex(0)
        self.ResultsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CentralWidget)

    def retranslateUi(self, CentralWidget):
        CentralWidget.setWindowTitle(_translate("CentralWidget", "Basic Regular Expression Tester", None))
        self.RegExpGroupBox.setTitle(_translate("CentralWidget", "Regular expresion and options", None))
        self.RegExpLabel.setText(_translate("CentralWidget", "Re&gular expression", None))
        self.RegExpLineEdit.setWhatsThis(_translate("CentralWidget", "Type here the regular expression in Python syntax", None))
        self.RegExpOptionsLabel.setText(_translate("CentralWidget", "Additional options", None))
        self.IgnoreCasePushButton.setToolTip(_translate("CentralWidget", "Do not distinguish between lowercase and uppercase letters.\n"
"For example : the pattern [A-Z] will match lowercase letters too.", None))
        self.IgnoreCasePushButton.setStatusTip(_translate("CentralWidget", "Click to select \'Ignore case\' option", None))
        self.IgnoreCasePushButton.setText(_translate("CentralWidget", "&Ignore case", None))
        self.MultiLinePushButton.setToolTip(_translate("CentralWidget", "Make the pattern character \'^\' matches at the beginning of the string and\n"
"at the beginning of each line, and the pattern character \'$\' matches at the\n"
"end of the string and at the end of each line.", None))
        self.MultiLinePushButton.setStatusTip(_translate("CentralWidget", "Click to select \'Multiline mode\' option", None))
        self.MultiLinePushButton.setText(_translate("CentralWidget", "Multiline m&ode", None))
        self.DotAllPushButton.setToolTip(_translate("CentralWidget", "Make the \'.\' special character match any character at all, including a newline.", None))
        self.DotAllPushButton.setStatusTip(_translate("CentralWidget", "Click to select \'Dot matches all\' option", None))
        self.DotAllPushButton.setText(_translate("CentralWidget", "&Dot matches all", None))
        self.ASCIIOnlyPushButton.setToolTip(_translate("CentralWidget", "Make \\w, \\W, \\b, \\B, \\d, \\D, \\s and \\S perform ASCII-only\n"
"matching instead of full Unicode matching.", None))
        self.ASCIIOnlyPushButton.setStatusTip(_translate("CentralWidget", "Click to select \'ASCII only\' option", None))
        self.ASCIIOnlyPushButton.setText(_translate("CentralWidget", "&ASCII only", None))
        self.PasteTextPushButton.setStatusTip(_translate("CentralWidget", "Paste text from the clipboard", None))
        self.PasteTextPushButton.setText(_translate("CentralWidget", "Paste from\n"
"&clipboard", None))
        self.ResetTextPushButton.setStatusTip(_translate("CentralWidget", "Clear the text", None))
        self.ResetTextPushButton.setText(_translate("CentralWidget", "R&eset", None))
        self.MethodTabWidget.setTabText(self.MethodTabWidget.indexOf(self.TextTab), _translate("CentralWidget", "Input te&xt", None))
        self.FilePathLineEdit.setPlaceholderText(_translate("CentralWidget", "File path", None))
        self.FilePathPushButton.setStatusTip(_translate("CentralWidget", "Select a file", None))
        self.FilePathPushButton.setText(_translate("CentralWidget", "&Choose a file", None))
        self.ResetFilePathPushButton.setStatusTip(_translate("CentralWidget", "Clear the file path", None))
        self.ResetFilePathPushButton.setText(_translate("CentralWidget", "R&eset", None))
        self.MethodTabWidget.setTabText(self.MethodTabWidget.indexOf(self.FileTab), _translate("CentralWidget", "Load &from file", None))
        self.URLLineEdit.setPlaceholderText(_translate("CentralWidget", "URL", None))
        self.PasteURLPushButton.setStatusTip(_translate("CentralWidget", "Past URL from the clipboard", None))
        self.PasteURLPushButton.setText(_translate("CentralWidget", "Paste from &clipboard", None))
        self.ResetURLPushButton.setStatusTip(_translate("CentralWidget", "Clear the URL", None))
        self.ResetURLPushButton.setText(_translate("CentralWidget", "R&eset", None))
        self.DownloadProgressBar.setFormat(_translate("CentralWidget", "Downloading %v/%m bytes (%p%)", None))
        self.MethodTabWidget.setTabText(self.MethodTabWidget.indexOf(self.URLTab), _translate("CentralWidget", "Load from &URL", None))
        self.MatchesLimitLabel.setText(_translate("CentralWidget", "Results limit", None))
        self.MatchesLimitSpinBox.setStatusTip(_translate("CentralWidget", "Set the maximum number of results", None))
        self.NoMatchesLimitCheckBox.setStatusTip(_translate("CentralWidget", "Ignore the limit of the results", None))
        self.NoMatchesLimitCheckBox.setText(_translate("CentralWidget", "No &limit", None))
        self.GroupsCheckBox.setText(_translate("CentralWidget", "Sho&w matched groups", None))
        self.PositionsCheckBox.setText(_translate("CentralWidget", "Show po&sitions", None))
        self.FindMatchesPushButton.setText(_translate("CentralWidget", "Find &matches", None))
        self.ResetMatchesPushButton.setText(_translate("CentralWidget", "Rese&t results", None))
        self.ResultsTabWidget.setTabText(self.ResultsTabWidget.indexOf(self.MatchesTab), _translate("CentralWidget", "Fi&nd matches", None))
        self.ReplacementTextLabel.setText(_translate("CentralWidget", "Replace&ment text", None))
        self.ReplacementsLimitLabel.setText(_translate("CentralWidget", "Replacements limit", None))
        self.ReplacementsLimitSpinBox.setStatusTip(_translate("CentralWidget", "Set the maximum number of replacements", None))
        self.NoReplacementsLimitCheckBox.setStatusTip(_translate("CentralWidget", "Ignore the limit of the replacements", None))
        self.NoReplacementsLimitCheckBox.setText(_translate("CentralWidget", "No &limit", None))
        self.ReplacePushButton.setText(_translate("CentralWidget", "&Search and replace", None))
        self.ResetReplacementsPushButton.setText(_translate("CentralWidget", "Rese&t results", None))
        self.ResultsTabWidget.setTabText(self.ResultsTabWidget.indexOf(self.ReplaceTab), _translate("CentralWidget", "Search and &replace", None))
        self.SplitsLimitLabel.setText(_translate("CentralWidget", "Splits limit", None))
        self.SplitsLimitSpinBox.setStatusTip(_translate("CentralWidget", "Set the maximum number of splits", None))
        self.NoSplitsLimitCheckBox.setStatusTip(_translate("CentralWidget", "Ignore the limit of the splits", None))
        self.NoSplitsLimitCheckBox.setText(_translate("CentralWidget", "No &limit", None))
        self.SplitPushButton.setText(_translate("CentralWidget", "&Split text", None))
        self.ResetSplitPushButton.setText(_translate("CentralWidget", "Rese&t results", None))
        self.ResultsTabWidget.setTabText(self.ResultsTabWidget.indexOf(self.SplitTab), _translate("CentralWidget", "S&plit text", None))

