# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/bret.ui'
#
# Created: Tue Aug 12 18:32:51 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName(_fromUtf8("Window"))
        Window.resize(594, 472)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Window)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.RegExpGroupBox = QtGui.QGroupBox(Window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegExpGroupBox.sizePolicy().hasHeightForWidth())
        self.RegExpGroupBox.setSizePolicy(sizePolicy)
        self.RegExpGroupBox.setObjectName(_fromUtf8("RegExpGroupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.RegExpGroupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.RegExpLabel = QtGui.QLabel(self.RegExpGroupBox)
        self.RegExpLabel.setObjectName(_fromUtf8("RegExpLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.RegExpLabel)
        self.RegExpLineEdit = QtGui.QLineEdit(self.RegExpGroupBox)
        self.RegExpLineEdit.setObjectName(_fromUtf8("RegExpLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.RegExpLineEdit)
        self.RegExpOptionsLabel = QtGui.QLabel(self.RegExpGroupBox)
        self.RegExpOptionsLabel.setObjectName(_fromUtf8("RegExpOptionsLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.RegExpOptionsLabel)
        self.RegExpOptionsLayout = QtGui.QHBoxLayout()
        self.RegExpOptionsLayout.setObjectName(_fromUtf8("RegExpOptionsLayout"))
        self.IgnoreCasePushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.IgnoreCasePushButton.setCheckable(True)
        self.IgnoreCasePushButton.setObjectName(_fromUtf8("IgnoreCasePushButton"))
        self.RegExpOptionsLayout.addWidget(self.IgnoreCasePushButton)
        self.MultiLinePushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.MultiLinePushButton.setCheckable(True)
        self.MultiLinePushButton.setObjectName(_fromUtf8("MultiLinePushButton"))
        self.RegExpOptionsLayout.addWidget(self.MultiLinePushButton)
        self.DotAllPushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.DotAllPushButton.setCheckable(True)
        self.DotAllPushButton.setObjectName(_fromUtf8("DotAllPushButton"))
        self.RegExpOptionsLayout.addWidget(self.DotAllPushButton)
        self.ASCIIOnlyPushButton = QtGui.QPushButton(self.RegExpGroupBox)
        self.ASCIIOnlyPushButton.setCheckable(True)
        self.ASCIIOnlyPushButton.setObjectName(_fromUtf8("ASCIIOnlyPushButton"))
        self.RegExpOptionsLayout.addWidget(self.ASCIIOnlyPushButton)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.RegExpOptionsLayout)
        self.verticalLayout_3.addWidget(self.RegExpGroupBox)
        self.MethodTabWidget = QtGui.QTabWidget(Window)
        self.MethodTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.MethodTabWidget.setObjectName(_fromUtf8("MethodTabWidget"))
        self.TextTab = QtGui.QWidget()
        self.TextTab.setObjectName(_fromUtf8("TextTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.TextTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.TextEdit = QtGui.QPlainTextEdit(self.TextTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit.sizePolicy().hasHeightForWidth())
        self.TextEdit.setSizePolicy(sizePolicy)
        self.TextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.TextEdit.setObjectName(_fromUtf8("TextEdit"))
        self.horizontalLayout_2.addWidget(self.TextEdit)
        self.TextTabButtonsLayout = QtGui.QVBoxLayout()
        self.TextTabButtonsLayout.setObjectName(_fromUtf8("TextTabButtonsLayout"))
        self.PasteTextPushButton = QtGui.QPushButton(self.TextTab)
        self.PasteTextPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasteTextPushButton.sizePolicy().hasHeightForWidth())
        self.PasteTextPushButton.setSizePolicy(sizePolicy)
        self.PasteTextPushButton.setObjectName(_fromUtf8("PasteTextPushButton"))
        self.TextTabButtonsLayout.addWidget(self.PasteTextPushButton)
        self.ResetTextPushButton = QtGui.QPushButton(self.TextTab)
        self.ResetTextPushButton.setObjectName(_fromUtf8("ResetTextPushButton"))
        self.TextTabButtonsLayout.addWidget(self.ResetTextPushButton)
        self.horizontalLayout_2.addLayout(self.TextTabButtonsLayout)
        self.MethodTabWidget.addTab(self.TextTab, _fromUtf8(""))
        self.FileTab = QtGui.QWidget()
        self.FileTab.setObjectName(_fromUtf8("FileTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.FileTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.FilePathLineEdit = QtGui.QLineEdit(self.FileTab)
        self.FilePathLineEdit.setObjectName(_fromUtf8("FilePathLineEdit"))
        self.horizontalLayout_3.addWidget(self.FilePathLineEdit)
        self.FilePathPushButton = QtGui.QPushButton(self.FileTab)
        self.FilePathPushButton.setObjectName(_fromUtf8("FilePathPushButton"))
        self.horizontalLayout_3.addWidget(self.FilePathPushButton)
        self.ResetFilePathPushButton = QtGui.QPushButton(self.FileTab)
        self.ResetFilePathPushButton.setObjectName(_fromUtf8("ResetFilePathPushButton"))
        self.horizontalLayout_3.addWidget(self.ResetFilePathPushButton)
        self.MethodTabWidget.addTab(self.FileTab, _fromUtf8(""))
        self.URLTab = QtGui.QWidget()
        self.URLTab.setObjectName(_fromUtf8("URLTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.URLTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.URLLineEdit = QtGui.QLineEdit(self.URLTab)
        self.URLLineEdit.setObjectName(_fromUtf8("URLLineEdit"))
        self.horizontalLayout_4.addWidget(self.URLLineEdit)
        self.PasteURLPushButton = QtGui.QPushButton(self.URLTab)
        self.PasteURLPushButton.setEnabled(False)
        self.PasteURLPushButton.setObjectName(_fromUtf8("PasteURLPushButton"))
        self.horizontalLayout_4.addWidget(self.PasteURLPushButton)
        self.ResetURLPushButton = QtGui.QPushButton(self.URLTab)
        self.ResetURLPushButton.setObjectName(_fromUtf8("ResetURLPushButton"))
        self.horizontalLayout_4.addWidget(self.ResetURLPushButton)
        self.MethodTabWidget.addTab(self.URLTab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.MethodTabWidget)
        self.ResultsTabWidget = QtGui.QTabWidget(Window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultsTabWidget.sizePolicy().hasHeightForWidth())
        self.ResultsTabWidget.setSizePolicy(sizePolicy)
        self.ResultsTabWidget.setObjectName(_fromUtf8("ResultsTabWidget"))
        self.MatchesTab = QtGui.QWidget()
        self.MatchesTab.setObjectName(_fromUtf8("MatchesTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.MatchesTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.MatchesLayout = QtGui.QHBoxLayout()
        self.MatchesLayout.setObjectName(_fromUtf8("MatchesLayout"))
        self.MatchesLimitLabel = QtGui.QLabel(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatchesLimitLabel.sizePolicy().hasHeightForWidth())
        self.MatchesLimitLabel.setSizePolicy(sizePolicy)
        self.MatchesLimitLabel.setObjectName(_fromUtf8("MatchesLimitLabel"))
        self.MatchesLayout.addWidget(self.MatchesLimitLabel)
        self.MatchesLimitSpinBox = QtGui.QSpinBox(self.MatchesTab)
        self.MatchesLimitSpinBox.setEnabled(False)
        self.MatchesLimitSpinBox.setMinimum(1)
        self.MatchesLimitSpinBox.setObjectName(_fromUtf8("MatchesLimitSpinBox"))
        self.MatchesLayout.addWidget(self.MatchesLimitSpinBox)
        self.NoMatchesLimitCheckBox = QtGui.QCheckBox(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoMatchesLimitCheckBox.sizePolicy().hasHeightForWidth())
        self.NoMatchesLimitCheckBox.setSizePolicy(sizePolicy)
        self.NoMatchesLimitCheckBox.setChecked(True)
        self.NoMatchesLimitCheckBox.setObjectName(_fromUtf8("NoMatchesLimitCheckBox"))
        self.MatchesLayout.addWidget(self.NoMatchesLimitCheckBox)
        self.GroupsCheckBox = QtGui.QCheckBox(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupsCheckBox.sizePolicy().hasHeightForWidth())
        self.GroupsCheckBox.setSizePolicy(sizePolicy)
        self.GroupsCheckBox.setObjectName(_fromUtf8("GroupsCheckBox"))
        self.MatchesLayout.addWidget(self.GroupsCheckBox)
        self.verticalLayout.addLayout(self.MatchesLayout)
        self.MatchesTreeView = QtGui.QTreeView(self.MatchesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatchesTreeView.sizePolicy().hasHeightForWidth())
        self.MatchesTreeView.setSizePolicy(sizePolicy)
        self.MatchesTreeView.setObjectName(_fromUtf8("MatchesTreeView"))
        self.verticalLayout.addWidget(self.MatchesTreeView)
        self.MatchesButtonsLayout = QtGui.QHBoxLayout()
        self.MatchesButtonsLayout.setObjectName(_fromUtf8("MatchesButtonsLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.MatchesButtonsLayout.addItem(spacerItem)
        self.FindMatchesPushButton = QtGui.QPushButton(self.MatchesTab)
        self.FindMatchesPushButton.setEnabled(False)
        self.FindMatchesPushButton.setDefault(True)
        self.FindMatchesPushButton.setObjectName(_fromUtf8("FindMatchesPushButton"))
        self.MatchesButtonsLayout.addWidget(self.FindMatchesPushButton)
        self.ResetMatchesPushButton = QtGui.QPushButton(self.MatchesTab)
        self.ResetMatchesPushButton.setObjectName(_fromUtf8("ResetMatchesPushButton"))
        self.MatchesButtonsLayout.addWidget(self.ResetMatchesPushButton)
        self.verticalLayout.addLayout(self.MatchesButtonsLayout)
        self.ResultsTabWidget.addTab(self.MatchesTab, _fromUtf8(""))
        self.ReplaceTab = QtGui.QWidget()
        self.ReplaceTab.setObjectName(_fromUtf8("ReplaceTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ReplaceTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ReplacementsLayout = QtGui.QHBoxLayout()
        self.ReplacementsLayout.setObjectName(_fromUtf8("ReplacementsLayout"))
        self.ReplacementsLimitLabel = QtGui.QLabel(self.ReplaceTab)
        self.ReplacementsLimitLabel.setObjectName(_fromUtf8("ReplacementsLimitLabel"))
        self.ReplacementsLayout.addWidget(self.ReplacementsLimitLabel)
        self.ReplacementsLimitSpinBox = QtGui.QSpinBox(self.ReplaceTab)
        self.ReplacementsLimitSpinBox.setEnabled(False)
        self.ReplacementsLimitSpinBox.setMinimum(1)
        self.ReplacementsLimitSpinBox.setObjectName(_fromUtf8("ReplacementsLimitSpinBox"))
        self.ReplacementsLayout.addWidget(self.ReplacementsLimitSpinBox)
        self.NoReplacementsLimitCheckBox = QtGui.QCheckBox(self.ReplaceTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoReplacementsLimitCheckBox.sizePolicy().hasHeightForWidth())
        self.NoReplacementsLimitCheckBox.setSizePolicy(sizePolicy)
        self.NoReplacementsLimitCheckBox.setChecked(True)
        self.NoReplacementsLimitCheckBox.setObjectName(_fromUtf8("NoReplacementsLimitCheckBox"))
        self.ReplacementsLayout.addWidget(self.NoReplacementsLimitCheckBox)
        self.verticalLayout_2.addLayout(self.ReplacementsLayout)
        self.ReplacementsTextBrowser = QtGui.QTextBrowser(self.ReplaceTab)
        self.ReplacementsTextBrowser.setObjectName(_fromUtf8("ReplacementsTextBrowser"))
        self.verticalLayout_2.addWidget(self.ReplacementsTextBrowser)
        self.ReplaceButtonsLayout = QtGui.QHBoxLayout()
        self.ReplaceButtonsLayout.setObjectName(_fromUtf8("ReplaceButtonsLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ReplaceButtonsLayout.addItem(spacerItem1)
        self.ReplacePushButton = QtGui.QPushButton(self.ReplaceTab)
        self.ReplacePushButton.setEnabled(False)
        self.ReplacePushButton.setDefault(True)
        self.ReplacePushButton.setObjectName(_fromUtf8("ReplacePushButton"))
        self.ReplaceButtonsLayout.addWidget(self.ReplacePushButton)
        self.ResetReplacementsPushButton = QtGui.QPushButton(self.ReplaceTab)
        self.ResetReplacementsPushButton.setObjectName(_fromUtf8("ResetReplacementsPushButton"))
        self.ReplaceButtonsLayout.addWidget(self.ResetReplacementsPushButton)
        self.verticalLayout_2.addLayout(self.ReplaceButtonsLayout)
        self.ResultsTabWidget.addTab(self.ReplaceTab, _fromUtf8(""))
        self.SplitTab = QtGui.QWidget()
        self.SplitTab.setObjectName(_fromUtf8("SplitTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.SplitTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.SplitsLimitLabel = QtGui.QLabel(self.SplitTab)
        self.SplitsLimitLabel.setObjectName(_fromUtf8("SplitsLimitLabel"))
        self.horizontalLayout_5.addWidget(self.SplitsLimitLabel)
        self.SplitsLimitSpinBox = QtGui.QSpinBox(self.SplitTab)
        self.SplitsLimitSpinBox.setEnabled(False)
        self.SplitsLimitSpinBox.setObjectName(_fromUtf8("SplitsLimitSpinBox"))
        self.horizontalLayout_5.addWidget(self.SplitsLimitSpinBox)
        self.NoSplitsLimitCheckBox = QtGui.QCheckBox(self.SplitTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoSplitsLimitCheckBox.sizePolicy().hasHeightForWidth())
        self.NoSplitsLimitCheckBox.setSizePolicy(sizePolicy)
        self.NoSplitsLimitCheckBox.setChecked(True)
        self.NoSplitsLimitCheckBox.setObjectName(_fromUtf8("NoSplitsLimitCheckBox"))
        self.horizontalLayout_5.addWidget(self.NoSplitsLimitCheckBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.SplitResultsListView = QtGui.QListView(self.SplitTab)
        self.SplitResultsListView.setObjectName(_fromUtf8("SplitResultsListView"))
        self.verticalLayout_5.addWidget(self.SplitResultsListView)
        self.SplitButtonsLayout = QtGui.QHBoxLayout()
        self.SplitButtonsLayout.setObjectName(_fromUtf8("SplitButtonsLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.SplitButtonsLayout.addItem(spacerItem2)
        self.SplitPushButton = QtGui.QPushButton(self.SplitTab)
        self.SplitPushButton.setEnabled(False)
        self.SplitPushButton.setDefault(True)
        self.SplitPushButton.setObjectName(_fromUtf8("SplitPushButton"))
        self.SplitButtonsLayout.addWidget(self.SplitPushButton)
        self.ResetSplitPushButton = QtGui.QPushButton(self.SplitTab)
        self.ResetSplitPushButton.setObjectName(_fromUtf8("ResetSplitPushButton"))
        self.SplitButtonsLayout.addWidget(self.ResetSplitPushButton)
        self.verticalLayout_5.addLayout(self.SplitButtonsLayout)
        self.ResultsTabWidget.addTab(self.SplitTab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.ResultsTabWidget)
        self.RegExpLabel.setBuddy(self.RegExpLineEdit)
        self.MatchesLimitLabel.setBuddy(self.MatchesLimitSpinBox)
        self.ReplacementsLimitLabel.setBuddy(self.ReplacementsLimitSpinBox)

        self.retranslateUi(Window)
        self.MethodTabWidget.setCurrentIndex(0)
        self.ResultsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window)
        Window.setTabOrder(self.ResultsTabWidget, self.RegExpLineEdit)

    def retranslateUi(self, Window):
        Window.setWindowTitle(_translate("Window", "Basic Regular Expression Tester", None))
        self.RegExpGroupBox.setTitle(_translate("Window", "Regular expresion and text", None))
        self.RegExpLabel.setText(_translate("Window", "Re&gular expression", None))
        self.RegExpOptionsLabel.setText(_translate("Window", "Additional options", None))
        self.IgnoreCasePushButton.setText(_translate("Window", "&Ignore case", None))
        self.MultiLinePushButton.setText(_translate("Window", "Multiline m&ode", None))
        self.DotAllPushButton.setText(_translate("Window", "&Dot matches all", None))
        self.ASCIIOnlyPushButton.setText(_translate("Window", "&ASCII only", None))
        self.PasteTextPushButton.setText(_translate("Window", "Paste from\n"
"&clipboard", None))
        self.ResetTextPushButton.setText(_translate("Window", "R&eset text", None))
        self.MethodTabWidget.setTabText(self.MethodTabWidget.indexOf(self.TextTab), _translate("Window", "Input te&xt", None))
        self.FilePathLineEdit.setPlaceholderText(_translate("Window", "File path", None))
        self.FilePathPushButton.setText(_translate("Window", "&Choose a file", None))
        self.ResetFilePathPushButton.setText(_translate("Window", "R&eset", None))
        self.MethodTabWidget.setTabText(self.MethodTabWidget.indexOf(self.FileTab), _translate("Window", "Load &from file", None))
        self.URLLineEdit.setPlaceholderText(_translate("Window", "URL", None))
        self.PasteURLPushButton.setText(_translate("Window", "Paste from &clipboard", None))
        self.ResetURLPushButton.setText(_translate("Window", "R&eset", None))
        self.MethodTabWidget.setTabText(self.MethodTabWidget.indexOf(self.URLTab), _translate("Window", "Load from &URL", None))
        self.MatchesLimitLabel.setText(_translate("Window", "Results limit", None))
        self.NoMatchesLimitCheckBox.setText(_translate("Window", "No &limit", None))
        self.GroupsCheckBox.setText(_translate("Window", "Sho&w matched groups", None))
        self.FindMatchesPushButton.setText(_translate("Window", "Find &matches", None))
        self.ResetMatchesPushButton.setText(_translate("Window", "Rese&t results", None))
        self.ResultsTabWidget.setTabText(self.ResultsTabWidget.indexOf(self.MatchesTab), _translate("Window", "Fi&nd matches", None))
        self.ReplacementsLimitLabel.setText(_translate("Window", "Replacements limit", None))
        self.NoReplacementsLimitCheckBox.setText(_translate("Window", "No &limit", None))
        self.ReplacePushButton.setText(_translate("Window", "&Search and replace", None))
        self.ResetReplacementsPushButton.setText(_translate("Window", "Rese&t results", None))
        self.ResultsTabWidget.setTabText(self.ResultsTabWidget.indexOf(self.ReplaceTab), _translate("Window", "Search and &replace", None))
        self.SplitsLimitLabel.setText(_translate("Window", "Splits limit", None))
        self.NoSplitsLimitCheckBox.setText(_translate("Window", "No &limit", None))
        self.SplitPushButton.setText(_translate("Window", "&Split", None))
        self.ResetSplitPushButton.setText(_translate("Window", "Rese&t results", None))
        self.ResultsTabWidget.setTabText(self.ResultsTabWidget.indexOf(self.SplitTab), _translate("Window", "S&plit text", None))

